# Generated by Django 2.1 on 2019-07-08 15:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
            managers=[
                ('obj1', django.db.models.manager.Manager()),
            ],
        ),
    ]
