# Generated by Django 2.1 on 2019-07-08 15:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emp',
            managers=[
                ('sunny', django.db.models.manager.Manager()),
            ],
        ),
    ]
