# Generated by Django 2.1 on 2019-07-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20190708_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emp',
            name='ename',
            field=models.CharField(max_length=100),
        ),
    ]
