# Generated by Django 2.1 on 2019-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('productcost', models.IntegerField()),
                ('productcolor', models.CharField(max_length=20)),
                ('productdesc', models.CharField(max_length=50)),
            ],
        ),
    ]
