# Generated by Django 2.1 on 2019-07-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sfee', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiapp.Student')),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.IntegerField()),
            ],
            bases=('multiapp.student',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiapp.Emp')),
                ('cname', models.CharField(max_length=20)),
                ('csale', models.IntegerField()),
            ],
            bases=('multiapp.emp',),
        ),
    ]
